version: '3'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile-web-app
    ports:
      - 5001:5001
    depends_on:
      - back-end
  
  back-end:
    build: ./machine-learning-client
    ports:
      - 5002:5002